### ISSUE TITLE
Stable?

### ISSUE THREAD

**Issue by parkr** [Shopify/liquid-c#19]
The version on Rubygems.org is v0.0.2. This tells me, as a subscriber of SemVer, that it's not stable – that it should not be used in production environments.

Is this assumption true? The README does not discuss versioning practices. What do you think about versioning it (at least at the MAJOR level) alongside Liquid-ruby?

**Comment by pushrax** [comment]
It's a bit of an odd case because while it *is* stable, it isn't complete. However, since the API is hidden to regular users, calling the interface stable makes sense to me. I think keeping the major version in sync with Liquid is a very good idea.

**Comment by pushrax** [comment]
Just released 3.0.0, and set `master` (the development branch) to 4.0.0.alpha. This mirrors the development strategy in Liquid.

**Comment by parkr** [comment]
Whoo! Thanks, @pushrax :smile:
