### ISSUE TITLE
Release 4.0.0

### ISSUE THREAD

**Issue by pathawks** [Shopify/liquid-c#35]
It would be cool to release `4.0.0` :+1:

**Comment by fw42** [comment]
@pushrax thoughts?

**Comment by pushrax** [comment]
Why don't we include liquid-c by default in Liquid under the MRI platform? Then we can keep the version exactly compatible at all times.

Will cut a 4.0.0 anyway, no reason not to since we have released Liquid 4.

**Comment by pushrax** [comment]
This is done now, sorry it took literally a year.
