### ISSUE TITLE
Homepage & source code URLs missing in RubyGems listing

### ISSUE THREAD

**Issue by nirvdrum** [Shopify/liquid-c#36]
Please update the RubyGems metadata to include either the homepage or source code repo (or both). They're currently missing from https://rubygems.org/gems/liquid-c, making it hard to find the source code.

**Comment by dylanahsmith** [comment]
Sorry for missing that.  I agree that missing a source code link is annoying.  I've just pushed a commit to add the github repo as the homepage.

**Comment by nirvdrum** [comment]
Thanks for the quick fix!
